Bugfix/toastr css updates
Kareadita/Kavita-webui pull request #249
Opened 2021-06-24 21:19 UTC by therobbiedavis

Closes #248

2021-06-24 21:44 UTC, majora2007 commented
# Issues
- I'm seeing the background image flash on series-detail page, despite it not supposed to be showing there.
- The background image is too large, even after minification, it's sitting at 2MB which is causing a slow first paint and a flash on loading of login page. 
- Why are we adding a new font family?

2021-06-24 21:55 UTC, therobbiedavis commented
- Flashing should be fixed.
- I can resize the background image to help the size
- New font family is for "Kavita" branding

2021-06-24 21:57 UTC, majora2007 requested changes

2021-06-24 21:57 UTC, majora2007 commented on src/app/user-login/user-login.component.scss
> +        background-image: url('../../assets/images/alfons-morales-YLSwjSy7stw-unsplash-min.jpg');
Rename this file to be something more meaningful at first glance

2021-06-24 21:57 UTC, majora2007 commented on src/app/user-login/user-login.component.scss
> +            box-shadow: 0 0 0 0.2rem rgb(68 79 117 / 50%)
Please keep semicolons after all CSS styles.

2021-06-24 21:57 UTC, majora2007 commented on src/styles.scss
> +//@import '~ngx-toastr/toastr-bs4-alert';
Remove this dead code

2021-06-25 00:29 UTC, majora2007 approved these changes

2021-06-25 00:29 UTC, merged